spring:
  application:
    name: ChatService



  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/mongodb_chat_db?authSource=admin
#      password: admin
#      username: admin
#      authentication-database: admin

server:
  port: 8082