spring:
  application:
    name: ChatService



  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER:admin}:${MONGO_DB_PASSWORD:admin}@${DB_HOST:localhost}:27017/mongodb_chat_db?authSource=admin
#      password: admin
#      username: admin
#      authentication-database: admin

server:
  port: 8083