spring:
  application:
    name: UserService
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/UserDb
    username: ${POSTGRE_PASSWORD}
    password: ${POSTGRE_USERNAME}
    driverClassName: org.postgresql.Driver


Server:
  port: 8082